spring:
  application:
    name: bot-for-consultations
  datasource:
    url: jdbc:postgresql://localhost:5432/bot-for-consultations
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
jwt:
  secret: QfCzUQ8hGk9cG+2Yv4WmRoM6n8gqvZ5b8k4Yl2OigvYfFc7aKqFvQeV+5yQDx5l5M0E9hLmYVZl+K7z4s8qv0A==
  expiration: 3600
bot:
  name: consultations1_bot
  token: ${BOT_TOKEN}

google:
  calendar:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/oauth/google/callback}
    application-name: Bot for Consultations
    